# Generated by Django 3.1.5 on 2021-03-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zphoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
